service: wakeup-weather

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - polly:SynthesizeSpeech
      Resource: '*'

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  weather:
    handler: src/connectors/lambda/handler.handler
    events:
      - http:
          path: /
          method: get
